name: GitHub Actions Build and Deploy

# 触发条件: push 到 master 分支后
on:
  push:
    branches:
      - master

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # 选择要使用的 node 版本
          node-version: '14'

      # 打包静态文件
      - name: Build
        run: npm install && npm run build:github
          
          # 缓存 node_modules
               - name: Cache dependencies
               uses: actions/cache@v2
               id: yarn-cache
               with:
                 path: |
                   **/node_modules
                 key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                 restore-keys: |
                   ${{ runner.os }}-yarn-

          # 如果缓存没有命中，安装依赖
               - name: Install dependencies
                 if: steps.yarn-cache.outputs.cache-hit != 'true'
                 run: yarn --frozen-lockfile

          # 运行构建脚本
               - name: Build VuePress site
                 run: yarn docs:build

      # 部署
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          # GitHub 密钥
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # GitHub Pages 读取的分支
          BRANCH: gh-pages
          # 静态文件所在目录
          FOLDER: dist
